title: Elky's Blah Blah
description: C++, C#, Python, Ruby, and...
author: Elky Kim
github: https://github.com/elky84
about: Game server programmer. and a little client programming.
disqus_shortname: elky84
google_analytics: UA-67357923-2

enableTags: true
tagarray: [Programmer, Game Developer]

collections:
  project:
    output: true
    permalink: /project/:path/

# refs : http://fontawesome.io/icons/
social:
    - icon: fa-facebook
      link: "https://www.facebook.com/elky1984"
    - icon: fa-twitter
      link: "http://twitter.com/elky84"
    - icon: fa-linkedin
      link: "https://kr.linkedin.com/in/elky-96299bb1"
    - icon: fa-github
      link: "https://elky84.github.io"
    - icon: fa-steam
      link: "http://steamcommunity.com/id/elky84"

share:
  twitter_username: elky84
  fb_appid: 828191487218951

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://elky84.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist