# Dependencies
markdown:         kramdown
highlighter:      rouge

lang: en

# Setup
title:            Elky Essay
tagline:          'My Development essay. and histories.'
description:      'web & socket programming. and...'
url:              https://elky84.github.io
baseurl:          

author:
  name:           'Elky Kim'
  url:            https://elky84.github.io


disqus.shortname: elky

excerpt_separator: "<!-- more -->"
  
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap

sidebar_home_link:  true
#sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/elky84

